# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8e8a2c0dab3b84e108c14beaeb00942c81feb52300c96993a079a8628a0a1bf7efada6c67d2bde907f9a6457e56f6393e80a78ebd056529dbc78b85d51ebca

test:
  secret_key_base: 9a92204e4585fc7acbf404f89d3da3a48c9c906fc85c4e6c028c701dad08e607afc9e931dd7870711ed4d2e2dcf615f2f5ed92efd6981d77f453cb8f624acdaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
